const dirVars=require('./dir-vars.config.js');
const path=require('path');
const ExtractTextWebpackPlugin=require("extract-text-webpack-plugin");
module.exports={
    loaders:
    [
        {
            test:/\.jsx?$/,
            loader:'babel',
            include:dirVars.page,
            exclude:/node_modules/,
            query:{
                presets:['es2015','react'],
                plugins:[
                    ['import',[{libraryName:'antd',style:true}]],
                ],
                cacheDirectory:true
            }
        },
        {
            test:/\.css$/,
            include:dirVars.public,
            loader:ExtractTextWebpackPlugin.extract("css?minimized&-autoprefixer!postcss")
        },
        {
            test:/\.less$/,
            include:[dirVars.page,/node_modules/],
            loader:ExtractTextWebpackPlugin.extract("css?minimized&-autoprefixer!postcss!less")
        },
        {
            test:/\.(png|jpg|gif)$/,
            include:dirVars.public,
            loader:'url?limit=8192$name=./static/img/[hash].[ext]'
        },
        {
            test:/\.(woff|woff2|svg|eot|ttf)$/,
            include:dirVars.public,
            loader:'file?name=./static/fonts/[hash].[ext]'
        }
    ]
};
